services:
  mysql:
    image: mysql:8.4
    container_name: basketball_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: basketball_roster
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:

